"""
generate.py — Regenerate stable knowledge artifacts from the DB
Manual trigger only — never auto-regenerated.
"""

from pathlib import Path
from datetime import date
from rich.console import Console
from cortex.db import get_client
from cortex.query import retrieve

console = Console()
MAX_CHARS = 12000

STANDARDS_TOPICS = [
    {"query": "Angular coding standards component patterns",     "top_k": 4, "heading": "Angular"},
    {"query": "TypeScript conventions strict mode",             "top_k": 3, "heading": "TypeScript"},
    {"query": "MFE micro frontend architecture patterns",       "top_k": 3, "heading": "MFE"},
    {"query": "design system component usage guidelines",       "top_k": 4, "heading": "Design System"},
    {"query": "shared state management localStorage",           "top_k": 2, "heading": "State"},
    {"query": "accessibility WCAG requirements",                "top_k": 2, "heading": "Accessibility"},
    {"query": "unit testing coverage patterns",                 "top_k": 2, "heading": "Testing"},
    {"query": "CSS styling tokens utility classes",             "top_k": 2, "heading": "Styling"},
]

VISION_TOPICS = [
    {"query": "platform vision goals objectives",               "top_k": 4, "heading": "Vision"},
    {"query": "developer experience principles",                "top_k": 3, "heading": "DX"},
    {"query": "architecture principles decisions",              "top_k": 3, "heading": "Architecture"},
    {"query": "team conventions workflows",                     "top_k": 2, "heading": "Conventions"},
]

ADR_TOPICS = [
    {"query": "architecture decision record rationale",         "top_k": 5, "heading": "Decisions"},
    {"query": "technology choice selection",                    "top_k": 4, "heading": "Technology"},
    {"query": "pattern tradeoffs alternatives",                 "top_k": 3, "heading": "Patterns"},
    {"query": "infrastructure deployment configuration",        "top_k": 3, "heading": "Infrastructure"},
]

HEADERS = {
    "standards": """\
# Development Standards
> **Generated by cortex** · {date}
> Regenerate: `python3 cortex.py generate standards`

## Always Do
<!-- hand-author this section -->
- Use design system components — never native HTML elements
- Angular standalone component pattern — no NgModules in new code
- TypeScript strict mode — no `any` types
- WCAG 2.1 AA accessibility minimum

## Never Do
<!-- hand-author this section -->
- Share state directly between MFEs
- Inline styles — use design tokens only
- Import from another MFE bundle directly

## From Knowledge Base

""",
    "vision": """\
# Platform Vision
> **Generated by cortex** · {date}
> Regenerate: `python3 cortex.py generate vision`

## Summary
<!-- hand-author this section -->

## From Knowledge Base

""",
    "adr": """\
# Architecture Decision Records
> **Generated by cortex** · {date}
> Regenerate: `python3 cortex.py generate adr`

## From Knowledge Base

""",
}

OUTPUT_PATHS = {
    "standards": Path("cortex/knowledge/standards/STANDARDS.md"),
    "vision":    Path("cortex/knowledge/vision/VISION.md"),
    "adr":       Path("cortex/knowledge/adrs/ADR-INDEX.md"),
}

TOPICS_MAP = {
    "standards": STANDARDS_TOPICS,
    "vision":    VISION_TOPICS,
    "adr":       ADR_TOPICS,
}


def generate(artifact: str, confirm: bool = True) -> bool:
    output_path = OUTPUT_PATHS[artifact]
    topics = TOPICS_MAP[artifact]
    header = HEADERS[artifact].format(date=date.today().isoformat())

    if output_path.exists() and confirm:
        answer = console.input(
            f"[yellow]⚠ {output_path} exists. Overwrite?[/yellow] [y/N]: "
        ).strip().lower()
        if answer != "y":
            console.print("[dim]Skipped.[/dim]")
            return False

    console.print(f"\n[cyan]cortex generate {artifact}[/cyan]\n")

    try:
        get_client().get_collection("cortex")
        db_ok = True
    except Exception:
        db_ok = False
        console.print("[yellow]⚠ No DB found — generating header-only artifact.[/yellow]")

    sections = [header]
    total = len(header)

    if db_ok:
        for t in topics:
            if total >= MAX_CHARS:
                break
            chunks = retrieve(query=t["query"], top_k=t["top_k"], silent=True)
            if not chunks:
                continue
            section = [f"### {t['heading']}\n"]
            for c in chunks:
                entry = f"**Source:** `{c['source']}` (relevance: {c['score']})\n\n{c['text']}\n\n---\n\n"
                if total + len(entry) > MAX_CHARS:
                    break
                section.append(entry)
                total += len(entry)
            sections.extend(section)
            console.print(f"  [green]✓[/green] {t['heading']}")

    content = "\n".join(sections)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    console.print(f"\n[green]✓ Written:[/green] [yellow]{output_path}[/yellow]\n")
    return True


def cmd_standards(yes: bool = False): generate("standards", confirm=not yes)
def cmd_vision(yes: bool = False):    generate("vision", confirm=not yes)
def cmd_adr(yes: bool = False):       generate("adr", confirm=not yes)
def cmd_all(yes: bool = False):
    for a in ["standards", "vision", "adr"]:
        generate(a, confirm=not yes)
